version: '3'
services:

  db:
    image: "mysql:latest"
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      restart: always
    ports:
      - 8081:80

  auth-microservice:
    build: ./auth-microservice
    container_name: auth-microservice
    ports:
      - 8080:8080
    links:
      - db

volumes:
  dbdata:
